import Head from 'next/head';
import Navbar2 from '../../components/navbar2';

export default function Home() {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Navbar2 />
      <div className='h-screen dark:bg-gray-900'>
        <div className='grid justify-items-center'>
          <div className='dark:bg-gray-500 border-2 p-5 flex text-2xl w-2/3'>
            <div>
              <h1>Time capsule</h1>
            </div>
            <div className='ml-2'>
              <h1>Time capsule</h1>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
